var kanjiList  = {
  'turtle': {
    'kanji': '亀',
    'radical': '亀',
    'strokes': '11',
    'readings': 'キ、かめ',
    'english': 'TURTLE',
    'word1': '亀',
    'word1read': 'かめ',
    'word1english': 'turtle',
    'word2': '亀裂',
    'word2read': 'きれつ',
    'word2english': 'crack, fissure',
    'word3': '亀の甲より年の功',
    'word3read': 'かめ　の　こう　より　とし　の　こう',
    'word3english': 'The older, the wiser.',
    'illustText': 'Animals like the turtle make up many of the 象形文字(shou-kei-mo-ji), or "picture characters." They represent a straight depiction of a creature, item or phenonenom, and were some of the earliest characters ever created.',
    'oldFormText': 'The bone script character (left) began as simply a drawing of a turtle. The seal script (middle) form is streamlined, but still retains a distinct head, shell, and tail. The modern form (right) is further simplified, with parts of the turtle replaced with common elements to represent the headク body田 and tail乚.'
  },

  'lightning':{
    'kanji': '雷',
    'radical': '雨',
    'strokes': '13',
    'readings': 'デン',
    'english': 'LIGHTNING, ELECTRICITY',
    'word1': '電気',
    'word1read': 'でんき',
    'word1english': 'electricity',
    'word2': '電車',
    'word2read': 'でんしゃ',
    'word2english': 'train',
    'word3': '電',
    'word3read': 'いなずま',
    'word3english': 'lightning',
    'illustText': 'Another reading for 電 outside of general usage is INAZUMA, which means lightning. This breaks down to INA(稲) "rice stalk" and ZUMA(妻) "spouse." It was thought that when a bolt touched down from the sky, it would impregnate the rice stalk, which could then bear fruit for the harvest.',
    'oldFormText': 'The rain 雨 radical is often used in kanji related to weather. The bottom half is a form of 申, which was designed in the shape of a lightning bolt. Lightning was thought to be a message from the gods, so 申す means "to say" and the 申 element is found in the kanji for god 神.'   
  },

  'old':{
    'kanji': '老',
    'radical': '耂',
    'strokes': '6',
    'readings': 'ロウ、お(いる)、ふ(ける)',
    'english': 'OLD',
    'word1': '老眼鏡',
    'word1read': 'ろうがんきょう',
    'word1english': 'reading glasses',
    'word2': '年老い',
    'word2read': 'としおい',
    'word2english': 'old person',
    'word3': '老ける',
    'word3read': 'ふける',
    'word3english': 'to age, grow old',
    'illustText': 'What is considered "old age" has drastically shifted since ancient times, and some of our best music is still put out by elderly folk who have traded in their walking sticks for microphone stands.',
    'oldFormText': 'The bone script shows an old man with long hair supported by a cane. In seal script, this became ヒ, which some theories say is a dead body (like in death→死), as old people are "approching death."'   
  },
  'travel':{
    'kanji': '旅',
    'radical': '方',
    'strokes': '6',
    'readings': 'リョ、たび',
    'english': 'TRAVEL',
    'word1': '旅行',
    'word1read': 'りょこう',
    'word1english': 'trip',
    'word2': '旅館',
    'word2read': 'りょかん',
    'word2english': 'traditional Japanese inn',
    'word3': '良い旅を！',
    'word3read': 'よいたびを！',
    'word3english': 'Have a nice trip!',
    'illustText': 'Even in modern-day Japan, tour guides leading groups using flags is a common sight at the train station or airport.',
    'oldFormText': 'The bone script character shows a flag with two people standing beside it indicating a succession of people. This morphed into a flag-bearer left, a flag waving top-right, and two people bottom-right.'
  },
  'prefecture':{
    'kanji': '県',
    'radical': '目',
    'strokes': '9',
    'readings': 'ケン',
    'english': 'PREFECTURE',
    'word1': '都道府県',
    'word1read': 'とどうふけん',
    'word1english': 'prefectures of Japan',
    'word2': '静岡県',
    'word2read': 'しずおかけん',
    'word2english': 'Shizuoka prefecture',
    'word3': '縣さん',
    'word3read': 'あがたさん',
    'word3english': 'Mr. Agata',
    'illustText': 'The head of a criminal would be put on display at the border as a warning for those entering a territory. In this way, 県 came to represent the demarkation of administrative districts.',
    'oldFormText': 'The bronze script character shows a severed head hanging from a rope. This is reflected in the old form 縣, which is the head(首) element upside-down next to thread(系). The current simplified form omits the thread portion.'
  },
  'heavy':{
    'kanji': '重',
    'radical': '里',
    'strokes': '9',
    'readings': 'ジュウ、チョウ、え、おも(い)、かさ(ねる)、かさ(なる)',
    'english': 'HEAVY',
    'word1': '重い',
    'word1read': 'おもい',
    'word1english': 'heavy',
    'word2': '体重',
    'word2read': 'たいじゅう',
    'word2english': 'body weight',
    'word3': '貴重',
    'word3read': 'きちょう',
    'word3english': 'precious',
    'illustText': 'This kanji depicts a person bearing a heavy sack. It can represent physical weight, emotional weight or value. The Japanese meanings of KASANERU/KASANARU mean to "stack, pile up or overlap" and the reading E is one instance in a stack, e.g., 紙一重(KAMI HITO E), "paper thin" is literally one一 sheet重 of paper紙.',
    'oldFormText': 'Above is the seal script version of 重. It is a combintation of a person and a satchel. Most dictionaries divide the character into 1000(千) + village(里) and categorize under the 里 radical. Though unrelated to the original meaning of 重, ruling over 1,000 villages would be a heavy burden to bear.'
  },
  'hatch':{
    'kanji': '孵',
    'radical': '子',
    'strokes': '14',
    'readings': 'フ、かえ(す)、かえ(る)',
    'english': 'HATCH, INCUBATE',
    'word1': '孵す',
    'word1read': 'かえす',
    'word1english': 'to hatch, incubate',
    'word2': '孵化',
    'word2read': 'ふか',
    'word2english': 'hatching, incubation',
    'word3': '孵化装置',
    'word3read': 'ふかそうち',
    'word3english': 'incubator',
    'illustText': '孵 falls outside the "general use" set of kanji and is commonly replaced with hiragana. For example, you may see "incubation" from the vocabulary list writtien as 「ふ化」 in newspapers and TV captions.',
    'oldFormText': 'Above is an assembled seal script form of 孵. The left is egg(卵), a character thought to be based on frog eggs. The right side is a combination of a hand and a child. Together, it represents outside influence on the incubation and birthing process.'
  },

  'together':{
    'kanji': '共',
    'radical': '',
    'strokes': '6',
    'readings': 'とも',
    'english': 'TOGETHER, BOTH',
    'word1': '',
    'word1read': '',
    'word1english': '',
    'word2': '',
    'word2read': '',
    'word2english': '',
    'word3': '',
    'word3read': '',
    'word3english': '',
    'oldFormText': 'The seal script shows two hands lifting up a large offering. This can be interpreted as using BOTH hands or working TOGETHER.',
    'illustText': '共 is commonly used in TOMO NI (共に) "together" and FUTARI TOMO (二人共) "both of you/us", but is often written in hiragana.'
  },

  'on hand':{
    'kanji': '携',
    'radical': '扌',
    'strokes': '',
    'readings': '',
    'english': 'ON HAND',
    'word1': '',
    'word1read': '',
    'word1english': '',
    'word2': '',
    'word2read': '',
    'word2english': '',
    'word3': '',
    'word3read': '',
    'word3english': '',
    'oldFormText': 'This kanji is a combination of three parts: a bird, a pedestal and a hand. The hand radical indicates action or usage. The bird on the pedestal is used in ornithomancy. Ornithomancy is the ancient practice of fortunetelling by interpreting the behavior of birds. Ancient Chinese would rely on flight paths to determine many things, including how to mobilize military units. Nowadays we can simply pull out our smartphones and check GPS, but back then, birds were a key source of information.',
    'illustText': '携 is roughly equivalent to "on hand" as in having something "on hand" (CARRY) or being "on hand" to help another (PARTICIPATE). It is the KEI in KEITAI DENWA (携帯電話) "mobile phone."' 
  }
};
